name: Tests

on:
  workflow_call:

jobs:

  Test:
    container: ubuntu:bionic
    runs-on:
      - self-hosted
      - Linux
      - X64

    strategy:
      fail-fast: false
      matrix:
        test:
          - docs
          - testarch
          - tests
          - ice40
          - xc7
          - xc7-vendor
          - xc7a200t
          - xc7a200t-vendor
          - ql

    name: ${{ matrix.test }}

    env:
      MAX_CORES: 80
      GHA_EXTERNAL_DISK: "tools"

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v3
        with:
          submodules: recursive


  Install:
    needs: Test
    container: ubuntu:bionic
    runs-on:
      - self-hosted
      - Linux
      - X64

    env:
      MAX_CORES: 80
      GHA_EXTERNAL_DISK: "tools"
      GHA_SA: "gh-sa-f4pga-arch-defs-ci"

    steps:

      - name: 🚀 Update latest URL files
        if: github.event_name == 'push'
        run: mkdir -p gs://${{ secrets.GCP_STORAGE_BUCKET }}
